export const Layout = {
  VERTICAL_TWO_COLUMN: 'VERTICAL_TWO_COLUMN',
  VERTICAL_ONE_COLUMN: 'VERTICAL_ONE_COLUMN',
  HORIZONTAL_JUSTIFIED: 'HORIZONTAL_JUSTIFIED',
  HORIZONTAL_LEFT_ALIGNED: 'HORIZONTAL_LEFT_ALIGNED',
};
