export const FormControlType = {
  RADIO: 'radio',
  CHECKBOX: 'checkbox',
  SELECT: 'select',
  FILE: 'file',
  DATE: 'date',
  DATETIME: 'date-time',
  TEL: 'tel',
  NUMBER: 'number',
  HIDDEN: 'hidden',
  PASSWORD: 'password',
  TEXT: 'text',
  TEXTAREA: 'textarea',
  UPLOAD: 'upload',
};
